//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure." +
                            "Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   A physical hardware device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomDeviceDescription {
            get {
                return ResourceManager.GetString("CustomDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://azure.microsoft.com/documentation/articles/iot-suite-connecting-devices/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomDeviceInstructionsUrl {
            get {
                return ResourceManager.GetString("CustomDeviceInstructionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomDeviceName {
            get {
                return ResourceManager.GetString("CustomDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device {0} is already registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceAlreadyRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceAlreadyRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device {0} is not registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceNotRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceNotRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was an error while registering device {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceRegistrationExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceRegistrationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Enabled State must be set. Please select Enabled or Disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledStateNotSetError {
            get {
                return ResourceManager.GetString("EnabledStateNotSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software to simulate a device. Easily extensible for arbitrary events and commands; can run in a Windows Azure worker role. To create a simulated device, please follow the cooler sample instructions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SimulatedDeviceDescription {
            get {
                return ResourceManager.GetString("SimulatedDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulated Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SimulatedDeviceName {
            get {
                return ResourceManager.GetString("SimulatedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device {0} does not support the command {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsupportedCommandExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedCommandExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device already exists in the device registry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationDeviceExists {
            get {
                return ResourceManager.GetString("ValidationDeviceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeviceID cannot be empty or null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationDeviceIdMissing {
            get {
                return ResourceManager.GetString("ValidationDeviceIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more validation errors occured for device {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionMessage", resourceCulture);
            }
        }
    }
}
